{
 "title": "JMeter_Promethius_Grafana 333333333333333333312",
 "description": "A grafana dashboard to inspect jmeter metrics via prometheus ",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "label",
    "label": "label",
    "query": {
     "query": "label_values(jmeter_count_total, label)"
    }
   },
   {
    "name": "label_2",
    "label": "label_2",
    "query": {
     "query": "label_values(jmeter_count_total, label)"
    }
   },
   {
    "name": "label_3",
    "label": "label_3",
    "query": {
     "query": "label_values(jmeter_count_total, label)"
    }
   },
   {
    "name": "intervel_for_requests",
    "label": "interval_for_requests",
    "query": "1s,3s,5s,10s,30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Threads v2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(jmeter_threads{state=\"active\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(jmeter_threads{state=\"active\"})"
    }
   ]
  },
  {
   "title": "conteiners count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\".+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total Request ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(jmeter_count_total{})" }
   ]
  },
  {
   "title": "Failure Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(jmeter_failure_total{})" }
   ]
  },
  {
   "title": "Failure Rate % v2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(jmeter_failure_total{}))*100/(sum(jmeter_count_total{}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Rate %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(jmeter_failure_total[$__interval]))/sum(rate(jmeter_count_total[$__interval])))"
    }
   ]
  },
  {
   "title": "Failure Rate % to time series",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "(sum(rate(jmeter_failure_total[$__interval]))/sum(rate(jmeter_count_total[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "webtours cpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "cpu usage v2",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[1m])) by (name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "webtours ram", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "webtours ram_usage_%",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((container_memory_usage_bytes{image=\"ihusainov/webtours:v2\"})/container_spec_memory_limit_bytes{image=\"ihusainov/webtours:v2\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "webtours ram_usage_mb",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{image=\"ihusainov/webtours:v2\"})/1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "webtours ram_limit_mb",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 55 },
   "targets": [
    {
     "expr": "(container_spec_memory_limit_bytes{image=\"ihusainov/webtours:v2\"})/1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "webtours memory_rss",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 55 },
   "targets": [
    {
     "expr": "container_memory_rss{image=\"ihusainov/webtours:v2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "webtours fs io",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "webtours fs_io_current",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "container_fs_io_current{image=\"ihusainov/webtours:v2\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "webtours fs_io_time_weighted_seconds_total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 46 },
     "targets": [
      {
       "expr": "container_fs_io_time_weighted_seconds_total{image=\"ihusainov/webtours:v2\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "disk io v2",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "sum(rate(container_fs_write_seconds_total{image=\"ihusainov/webtours:v2\"}[1m])) by (name) * 100",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(container_fs_read_seconds_total{image=\"ihusainov/webtours:v2\"}[1m])) by (name) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "webtours fs_io_time_seconds_total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "container_fs_io_time_seconds_total{image=\"ihusainov/webtours:v2\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Response times by Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "90th Pct response times",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9,rate(jmeter_summary_histogram_bucket{label=~\"$label\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(jmeter_count_total{label=~\"$label\"}[$__rate_interval])) by (label)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(jmeter_summary_sum{label=~\"$label\"}[$__rate_interval])) by (label)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Load Test Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "90th Percentile  Response Time ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.9,rate(jmeter_summary_histogram_bucket{label=~\"$label\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(jmeter_count_total{label=~\"$label_2\"}[$__rate_interval]))",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Avg. Response Time ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(jmeter_summary_sum{label=~\"$label\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jmeter Aggregate Report",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(label)((jmeter_count_total{label=~\"$label\"}))"
    },
    {
     "expr": "avg(jmeter_summary{label=~\"$label\"}) by (label)"
    },
    {
     "expr": "avg(jmeter_summary{label=~\"$label\", quantile=\"0.9\"}) by (label)"
    },
    {
     "expr": "min(jmeter_summary{label=~\"$label\"}) by (label)"
    },
    {
     "expr": "max(jmeter_summary{label=~\"$label\"}) by (label)"
    },
    {
     "expr": "sum by(label)(increase(jmeter_count_total[$__range]))"
    }
   ]
  },
  {
   "title": "Фактическая интенсивность в тесте",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 129 },
   "targets": [
    {
     "expr": "sum(increase(jmeter_count_total{label=\"TC_home_page\"}[$__range])) / sum(jmeter_threads{state=\"active\"})*10"
    },
    {
     "expr": "sum(increase(jmeter_count_total{label=\"TC_login\"}[$__range])) / sum(jmeter_threads{state=\"active\"})*10"
    },
    {
     "expr": "sum(increase(jmeter_count_total{label=\"TC_flights\"}[$__range])) / sum(jmeter_threads{state=\"active\"})*10"
    },
    {
     "expr": "sum(increase(jmeter_count_total{label=\"TC_flights_find\"}[$__range])) / sum(jmeter_threads{state=\"active\"})*10"
    },
    {
     "expr": "sum(increase(jmeter_count_total{label=\"TC_choose_available_flight\"}[$__range])) / sum(jmeter_threads{state=\"active\"})*10"
    },
    {
     "expr": "sum(increase(jmeter_count_total{label=\"TC_payment_details\"}[$__range])) / sum(jmeter_threads{state=\"active\"})*10"
    },
    {
     "expr": "sum(increase(jmeter_count_total{label=\"TC_itinerary\"}[$__range])) / sum(jmeter_threads{state=\"active\"})*10"
    },
    {
     "expr": "sum(increase(jmeter_count_total{label=\"TC_itinerary_delete_one (first)\"}[$__range])) / sum(jmeter_threads{state=\"active\"})*10",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "sum(increase(jmeter_count_total{label=\"TC_logout\"}[$__range])) / sum(jmeter_threads{state=\"active\"})*10"
    },
    {
     "expr": "sum(increase(jmeter_count_total{label=\"TC_open_register_page\"}[$__range])) / sum(jmeter_threads{state=\"active\"})*10"
    },
    {
     "expr": "sum(increase(jmeter_count_total{label=\"TC_fill_register_page\"}[$__range])) / sum(jmeter_threads{state=\"active\"})*10",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(jmeter_count_total{label=\"TC_next_page_after_register_completion\"}[$__range])) / sum(jmeter_threads{state=\"active\"})*10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Request Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jmeter_failure_total) by (label)"
    }
   ]
  },
  { "title": "Errors Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 } },
  {
   "title": "Error by Transactions",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 141 },
   "targets": [
    {
     "expr": "sum by (code,label) (jmeter_failure_total)"
    }
   ]
  },
  {
   "title": "Errors Count",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 146 },
   "targets": [
    {
     "expr": "sum by (code) (jmeter_failure_total)"
    }
   ]
  },
  {
   "title": "Test farm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC % time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{job=~\"jmeter2\"}[1m])",
       "legendFormat": "{{instance}} - {{gc}} "
      }
     ]
    },
    {
     "title": "JVM heap  - free memory by pool",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(jvm_memory_pool_bytes_committed {job=~\"jmeter2\"}) - (jvm_memory_pool_bytes_used{job=~\"jmeter2\"}) ",
       "legendFormat": "{{instance}} - {{pool}}"
      }
     ]
    },
    {
     "title": "JVM heap -  used memory by pool",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(jvm_memory_pool_bytes_used{job=\"jmeter2\"}) ",
       "legendFormat": "{{instance}} - {{pool}}"
      }
     ]
    },
    {
     "title": "JVM free memory",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(jvm_memory_bytes_max {job=\"jmeter2\"}) - (jvm_memory_bytes_used{job=\"jmeter2\"})",
       "legendFormat": "{{instance}} - {{area}}"
      }
     ]
    }
   ]
  }
 ]
}