#http://localhost:8050 or http://192.168.88.248:8050
transactionServiceAddress=http://localhost:8050
openapi.local-url=http://localhost:8040
openapi.dev-url=http://192.168.88.248:8040
#port for not auth app
server.port=8040
spring.application.name=authapp
management.metrics.tags.application=${spring.application.name}
management.endpoints.web.exposure.include=*
management.endpoint.health.show.details=always
management.tracing.sampling.probability=1.0